/* eslint-disable */
// prettier-ignore
// This file is automatically generated by typings-for-css-modules.
// Don't change it directly!

declare namespace StylesModuleSassNamespace {
  export interface IStylesModuleSass {
    'badge': string;
    'badgeInput': string;
    'blackFrame': string;
    'caption': string;
    'captionInput': string;
    'content': string;
    'editable': string;
    'greenBlue': string;
    'grey': string;
    'redFrame': string;
    'root': string;
    'title': string;
    'titleInput': string;
  }
}

declare const StylesModuleSassModule: StylesModuleSassNamespace.IStylesModuleSass & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StylesModuleSassNamespace.IStylesModuleSass
}

export = StylesModuleSassModule
